import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/app/components/Navbar";
import network from '@/app/assets/network.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{
        position: 'relative',
        minHeight: '100vh',
        margin: 0,
        padding: 0,
        overflow: 'hidden',
        fontFamily: inter.className,
      }}
    >
      <div
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundImage: `url(${network.src})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          zIndex: -1, // Ensures the image is behind other content
        }}
      />
      <div style={{ position: 'relative', zIndex: 1 }}>
        <Navbar />
      </div>
      <div className="mt-36">
      {children}
      </div>
    </div>
  );
}
